### ISSUE TITLE
Builds still using remote rather than local configs in some places

### ISSUE THREAD

**Issue by barndawgie** [esphome-econet/esphome-econet#377]
This message in the logs indicates we're still using remove configs during build in some cases:  
```
  Failed to load packages. econet_time.yaml does not exist in repository.
  econet_time: 
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    file: econet_time.yaml
```

**Comment by tronikos** [comment]
This doesn't currently happen right? It only happened in an earlier version of my PR. That's because the code only modifies the `econet:` see https://github.com/esphome-econet/esphome-econet/blob/a072331ee62c6a83e66641c10fc88c4a3da5df20/.github/workflows/build.yml#L51
I think we can close this and whenever we add another package we need to update that code.
